// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANnTQp3tiNS6UeionMpUNu2L9030AYv84',
    appId: '1:636657363748:web:3052c242a1d82789d721b1',
    messagingSenderId: '636657363748',
    projectId: 'sentimentanalysis-7ba59',
    authDomain: 'sentimentanalysis-7ba59.firebaseapp.com',
    storageBucket: 'sentimentanalysis-7ba59.appspot.com',
    measurementId: 'G-TTVZG04SMT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjKMiq6ucLQBSlamqkbfKKnS2bxZe1d8o',
    appId: '1:636657363748:android:8f08c20c28bc1ecdd721b1',
    messagingSenderId: '636657363748',
    projectId: 'sentimentanalysis-7ba59',
    storageBucket: 'sentimentanalysis-7ba59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA56sVjdCi8zU9Hj2Zjtw2Q7ydiO398G0o',
    appId: '1:636657363748:ios:85f9a5c88105b2b1d721b1',
    messagingSenderId: '636657363748',
    projectId: 'sentimentanalysis-7ba59',
    storageBucket: 'sentimentanalysis-7ba59.appspot.com',
    iosBundleId: 'com.example.sentimentanalysis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA56sVjdCi8zU9Hj2Zjtw2Q7ydiO398G0o',
    appId: '1:636657363748:ios:c5a87f70d40a9fa6d721b1',
    messagingSenderId: '636657363748',
    projectId: 'sentimentanalysis-7ba59',
    storageBucket: 'sentimentanalysis-7ba59.appspot.com',
    iosBundleId: 'com.example.sentimentanalysis.RunnerTests',
  );
}
